//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UGym_F
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlantillasEjercicios
    {
        public int PlantillaId { get; set; }
        public int EjercicioId { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.TimeSpan> Duracion { get; set; }
        public Nullable<int> Series { get; set; }
        public Nullable<int> Repeticiones { get; set; }
    
        public virtual Ejercicios Ejercicios { get; set; }
        public virtual Plantilla Plantilla { get; set; }
    }
}
