//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UGym_F
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservas
    {
        public int ReservaId { get; set; }
        public System.DateTime FechaReserva { get; set; }
        public System.TimeSpan HoraReservaInicio { get; set; }
        public System.TimeSpan HoraReservaFinal { get; set; }
        public int SocioId { get; set; }
        public int EspacioId { get; set; }
    
        public virtual Espacios Espacios { get; set; }
        public virtual Socios Socios { get; set; }
    }
}
