//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UGym_F
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rutinas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rutinas()
        {
            this.RutinasEjercicios = new HashSet<RutinasEjercicios>();
        }
    
        public int RutinaId { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int EmpleadoId { get; set; }
        public string Comentarios { get; set; }
        public Nullable<int> PlantillaId { get; set; }
    
        public virtual Empleados Empleados { get; set; }
        public virtual Plantilla Plantilla { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RutinasEjercicios> RutinasEjercicios { get; set; }
    }
}
