//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UGym_F
{
    using System;
    using System.Collections.Generic;
    
    public partial class SociosTipoPagos
    {
        public int SocioId { get; set; }
        public int PagoId { get; set; }
        public System.DateTime FechaPago { get; set; }
    
        public virtual Socios Socios { get; set; }
        public virtual TipoPagos TipoPagos { get; set; }
    }
}
