//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UGym_F
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anuncios
    {
        public int AnuncioId { get; set; }
        public string Nombre { get; set; }
        public string MediaEnlace { get; set; }
        public int EmpleadoId { get; set; }
    
        public virtual Empleados Empleados { get; set; }
    }
}
