//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UGym_F
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expediente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Expediente()
        {
            this.Socios = new HashSet<Socios>();
        }
    
        public int ExpedienteId { get; set; }
        public string CirugiasTipo { get; set; }
        public int CirugiasCantidad { get; set; }
        public string CirugiasDetalle { get; set; }
        public string FarmacosTipo { get; set; }
        public Nullable<int> FarmacosCantidad { get; set; }
        public string FarmacosAlergia { get; set; }
        public string EnfermedadCardiaca { get; set; }
        public string DoloresPecho { get; set; }
        public Nullable<int> HorasSentado { get; set; }
        public Nullable<int> CicloSueño { get; set; }
        public Nullable<int> EstresUltimoMes { get; set; }
        public Nullable<int> MotivacionEntrenar { get; set; }
        public string DificuladPerderGrasa { get; set; }
        public string NivelEnergiaUltimoMes { get; set; }
        public Nullable<int> PasosPorDia { get; set; }
        public string EjercicioTresMeses { get; set; }
        public string MotivoAsistencia { get; set; }
        public string AutoRegulacion { get; set; }
        public Nullable<int> Concentracion { get; set; }
        public Nullable<int> Alimentacion { get; set; }
        public string AlimentacionEstres { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Socios> Socios { get; set; }
    }
}
