//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UGym_F
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UGymEntities : DbContext
    {
        public UGymEntities()
            : base("name=UGymEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administradores> Administradores { get; set; }
        public virtual DbSet<Anuncios> Anuncios { get; set; }
        public virtual DbSet<Asistencia> Asistencia { get; set; }
        public virtual DbSet<Clases> Clases { get; set; }
        public virtual DbSet<CodigoQR> CodigoQR { get; set; }
        public virtual DbSet<ContactoEmergencia> ContactoEmergencia { get; set; }
        public virtual DbSet<Ejercicios> Ejercicios { get; set; }
        public virtual DbSet<Empleados> Empleados { get; set; }
        public virtual DbSet<EntrenadoresClases> EntrenadoresClases { get; set; }
        public virtual DbSet<Espacios> Espacios { get; set; }
        public virtual DbSet<Expediente> Expediente { get; set; }
        public virtual DbSet<InformesEvaluacion> InformesEvaluacion { get; set; }
        public virtual DbSet<InformesInbody> InformesInbody { get; set; }
        public virtual DbSet<InformesTerapia> InformesTerapia { get; set; }
        public virtual DbSet<PlanAlimentacion> PlanAlimentacion { get; set; }
        public virtual DbSet<Plantilla> Plantilla { get; set; }
        public virtual DbSet<PlantillasEjercicios> PlantillasEjercicios { get; set; }
        public virtual DbSet<Reportes> Reportes { get; set; }
        public virtual DbSet<Reservas> Reservas { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Rutinas> Rutinas { get; set; }
        public virtual DbSet<RutinasEjercicios> RutinasEjercicios { get; set; }
        public virtual DbSet<Socios> Socios { get; set; }
        public virtual DbSet<SociosEntrenadoresClases> SociosEntrenadoresClases { get; set; }
        public virtual DbSet<SociosRutinasEjercicios> SociosRutinasEjercicios { get; set; }
        public virtual DbSet<SociosTipoMembresias> SociosTipoMembresias { get; set; }
        public virtual DbSet<SociosTipoPagos> SociosTipoPagos { get; set; }
        public virtual DbSet<TipoMembresias> TipoMembresias { get; set; }
        public virtual DbSet<TipoPagos> TipoPagos { get; set; }
    }
}
