//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UGym_F
{
    using System;
    using System.Collections.Generic;
    
    public partial class Socios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Socios()
        {
            this.Asistencia = new HashSet<Asistencia>();
            this.InformesEvaluacion = new HashSet<InformesEvaluacion>();
            this.InformesInbody = new HashSet<InformesInbody>();
            this.InformesTerapia = new HashSet<InformesTerapia>();
            this.PlanAlimentacion = new HashSet<PlanAlimentacion>();
            this.Reservas = new HashSet<Reservas>();
            this.SociosRutinasEjercicios = new HashSet<SociosRutinasEjercicios>();
            this.SociosEntrenadoresClases = new HashSet<SociosEntrenadoresClases>();
            this.SociosRutinasEjercicios1 = new HashSet<SociosRutinasEjercicios>();
            this.SociosTipoMembresias = new HashSet<SociosTipoMembresias>();
            this.SociosTipoPagos = new HashSet<SociosTipoPagos>();
        }
    
        public int SocioId { get; set; }
        public int NumeroSocio { get; set; }
        public string Contraseña { get; set; }
        public string NombreCompleto { get; set; }
        public string Genero { get; set; }
        public int Cedula { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string Ocupacion { get; set; }
        public string ConoceGym { get; set; }
        public string Motivacion { get; set; }
        public string CorreoElectronico { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public int ContactoEmergenciaId { get; set; }
        public Nullable<int> ExpedienteId { get; set; }
        public Nullable<int> CodigoQRId { get; set; }
        public Nullable<int> EmpleadoId { get; set; }
        public int RolId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asistencia> Asistencia { get; set; }
        public virtual CodigoQR CodigoQR { get; set; }
        public virtual ContactoEmergencia ContactoEmergencia { get; set; }
        public virtual Empleados Empleados { get; set; }
        public virtual Expediente Expediente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InformesEvaluacion> InformesEvaluacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InformesInbody> InformesInbody { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InformesTerapia> InformesTerapia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanAlimentacion> PlanAlimentacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservas> Reservas { get; set; }
        public virtual Roles Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SociosRutinasEjercicios> SociosRutinasEjercicios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SociosEntrenadoresClases> SociosEntrenadoresClases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SociosRutinasEjercicios> SociosRutinasEjercicios1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SociosTipoMembresias> SociosTipoMembresias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SociosTipoPagos> SociosTipoPagos { get; set; }
    }
}
